name: Static Analysis Security Testing (SAST)

on:
  push:
    branches:
      - main

jobs:
  bandit_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install dependencies
        run: |
          pip install -r src/app/requirements.txt
          pip install bandit

      - name: Change working directory
        run: cd src/app
    
      - name: Show current directory
        run: pwd
      
      - name: List contents of /src/app
        run: ls -al


      - name: Run Bandit SAST scan
        run: bandit -r /src/app -f json -o bandit_report.json -ls

     # - name: Upload Bandit report
      #  uses: actions/upload-artifact@v2
      #  with:
         # name: bandit-report
         # path: bandit_report.json
